apiVersion: v1
kind: Service
metadata:
  name: ms-recette
  labels:
    app: ms-recette
spec:
  type: NodePort
  selector:
    app: ms-recette
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http

